# Generated by Django 4.1.6 on 2023-02-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0086_configtemplate'),
        ('dcim', '0168_interface_template_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='config_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='extras.configtemplate'),
        ),
    ]
