# Generated by Django 4.1.6 on 2023-02-12 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0086_configtemplate'),
        ('dcim', '0169_device_configtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicerole',
            name='config_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='device_roles', to='extras.configtemplate'),
        ),
    ]
